name: Daily Auto Commit

on:
  schedule:
    - cron: '30 18 * * *'  # 12:00 AM IST (6:30 PM UTC)
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create/Update commit file
        run: |
          echo "// Daily commit - $(TZ="Asia/Kolkata" date)" >> daily_commit.txt

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "chore: auto-commit at $(TZ="Asia/Kolkata" date)" || echo "No changes to commit"
          git push
